pipeline {
   agent any
  stages {
    stage('Pull deploy code') {
        echo "success"
    }
    stage('Stage 2') {
      steps {
        sh '''yarn install
yarn build:test
pm2 restart "my-nuxt"'''
      }
    }
  }
}