pipeline {
   agent any
  stages {
    stage('Pull deploy code') {
    steps {
    echo "success"
    }

    }
    stage('Stage 2') {
      steps {
        sh '''yarn install
yarn build:test
pm2 start yarn --name "my-nuxt" -- run:test
pm2 logs'''
      }
    }
  }
}